spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: iotgateway
mqtt:
  broker: ${MQTT_BROKER:tcp://localhost:1883}
  clientId: ${MQTT_CLIENT_ID:iot-gateway-server}
  topicFilter: sensors/+/data
